hydra:
  run:
    dir: hydra_output/

data:
  data_dir: ./input_clean
  asset_dir: ./assets
  seed: 0
  img_size: &image_size 224
  n_splits: 5
  save_top_k: 1
  total_step: None

model:
  type: cnn  # cnn, hybrid

cnn_model:
  backbone: swin_base_patch4_window7_224
  pretrained: True
  out_dim: 1
  hidden_size: 8
  dropout_rate: 0.5

hybrid_model:
  backbone: swin_base_patch4_window7_224
  embedder: tf_efficientnet_b4_ns
  img_size: *image_size
  out_dim: 1
  pretrained: True

train:
  exp_name: &exp_name test
  lr: 1e-5
  epoch: 20
  fold: 0
  batch_size: 20
  num_workers: 8
  weight_decay: 1e-5
  optimizer: radam    # sgd, adam, adamw, sam
  scheduler: cosine
  use_sam: False
  warmup_step: 100
  num_cycles: 1
  mixup_pct: 0.5
  mixup_alpha: 0.5
  cutmix_pct: 0.0
  cutmix_alpha: 1.0
  resizemix_pct: 0.0
  resizemix_alpha: 1.0

aug_kwargs:
  aug_train:
    RandomResizedCrop: {"height": *image_size, "width": *image_size, "scale": [0.5, 1.0], "ratio": [1.0, 1.0], "interpolation": 3}
    HorizontalFlip: {"p": 0.5}
    VerticalFlip: {"p": 0.5}
    ShiftScaleRotate: {"rotate_limit": 15, "shift_limit": 0.1}
    ColorJitter: {"brightness": 0.1, "contrast": 0.1, "saturation": 0.1}
    MotionBlur: {"p": 0.5}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}
    CoarseDropout: {"max_holes": 6, "max_height": 8, "max_width": 8}

  aug_val:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_test:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}


lgbm:
  feature_map_path: ./feature_maps
  exp_name: *exp_name

  params:
    num_iterations: 100000
    objective: regression
    metric: mse
    boosting: gbdt
    early_stopping_round: 1000
    learning_rate: 0.01
    first_metric_only: True
    feature_fraction: 0.7
    bagging_fraction: 0.7
    bagging_freq: 1